### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by mjhong0708** [mjhong0708/neural_iap#1]
# Overview

Tracking issue for things to do.

### Model implementation

- [ ] (P0) Behler-Parrinello NN (BPNN)
- [ ] (P0) Graph network (GN)
- [ ] (P2) Simple MPNN model
- [ ] (P2) Simple equivariant MPNN model
- [ ] (P1) Dimenet (and Dimenet++)
- [ ] (P2) Gemnet
- [ ] (P0) Painn
- [ ] (P1) Nequip

### Training

- [ ] (P1) High-level training API
- [ ] (P2) Better way to handle energy shift
- [ ] (P2) Add scaling features

### Code style & docs

- [ ] (P0) Unify import style
- [ ] (P1) Add docstring to all methods
- [ ] (P1) Add type annotations

### Misc

- [ ] (P2) Write tests
